name: forexthirdaplication
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts:
  provider: ^6.0.5
  intl:
  flutter_svg: ^2.0.7
  flutter_inappwebview: ^5.7.2+3
  rx_shared_preferences: ^3.0.0
  smooth_page_indicator:
  onesignal_flutter: ^3.5.1
  http:
  dio:
  shared_preferences: ^2.2.1
  json_serializable:
  json_annotation:
  build_runner:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/